source = ~/.cache/wal/colors-hyprland.conf

background = $background
base = $background
text = $foreground
alternate_base = $background
bright_text = $color4
accent = $color1
accent_secondary = $color2
